function bar(){ busybox ar $args }
function barch(){ busybox arch $args }
function bascii(){ busybox ascii $args }
function bash(){ busybox ash $args }
function bawk(){ busybox awk $args }
function bbase32(){ busybox base32 $args }
function bbase64(){ busybox base64 $args }
function bbasename(){ busybox basename $args }
function bbash(){ busybox bash $args }
function bbc(){ busybox bc $args }
function bbunzip2(){ busybox bunzip2 $args }
function bbusybox(){ busybox busybox $args }
function bbzcat(){ busybox bzcat $args }
function bbzip2(){ busybox bzip2 $args }
function bcal(){ busybox cal $args }
function bcat(){ busybox cat $args }
function bchattr(){ busybox chattr $args }
function bchmod(){ busybox chmod $args }
function bcksum(){ busybox cksum $args }
function bclear(){ busybox clear $args }
function bcmp(){ busybox cmp $args }
function bcomm(){ busybox comm $args }
function bcp(){ busybox cp $args }
function bcpio(){ busybox cpio $args }
function bcrc32(){ busybox crc32 $args }
function bcut(){ busybox cut $args }
function bdate(){ busybox date $args }
function bdc(){ busybox dc $args }
function bdd(){ busybox dd $args }
function bdf(){ busybox df $args }
function bdiff(){ busybox diff $args }
function bdirname(){ busybox dirname $args }
function bdos2unix(){ busybox dos2unix $args }
function bdpkg(){ busybox dpkg $args }
function bdpkg-deb(){ busybox dpkg-deb $args }
function bdu(){ busybox du $args }
function becho(){ busybox echo $args }
function bed(){ busybox ed $args }
function begrep(){ busybox egrep $args }
function benv(){ busybox env $args }
function bexpand(){ busybox expand $args }
function bexpr(){ busybox expr $args }
function bfactor(){ busybox factor $args }
function bFALSE(){ busybox FALSE $args }
function bfgrep(){ busybox fgrep $args }
function bfind(){ busybox find $args }
function bfold(){ busybox fold $args }
function bfree(){ busybox free $args }
function bfsync(){ busybox fsync $args }
function bftpget(){ busybox ftpget $args }
function bftpput(){ busybox ftpput $args }
function bgetopt(){ busybox getopt $args }
function bgrep(){ busybox grep $args }
function bgroups(){ busybox groups $args }
function bgunzip(){ busybox gunzip $args }
function bgzip(){ busybox gzip $args }
function bhd(){ busybox hd $args }
function bhead(){ busybox head $args }
function bhexdump(){ busybox hexdump $args }
function bhttpd(){ busybox httpd $args }
function biconv(){ busybox iconv $args }
function bid(){ busybox id $args }
function binotifyd(){ busybox inotifyd $args }
function binstall(){ busybox install $args }
function bipcalc(){ busybox ipcalc $args }
function bjn(){ busybox jn $args }
function bkill(){ busybox kill $args }
function bkillall(){ busybox killall $args }
function bless(){ busybox less $args }
function blink(){ busybox link $args }
function bln(){ busybox ln $args }
function blogname(){ busybox logname $args }
function bls(){ busybox ls $args }
function blsattr(){ busybox lsattr $args }
function blzcat(){ busybox lzcat $args }
function blzma(){ busybox lzma $args }
function blzop(){ busybox lzop $args }
function blzopcat(){ busybox lzopcat $args }
function bmake(){ busybox make $args }
function bman(){ busybox man $args }
function bmd5sum(){ busybox md5sum $args }
function bmkdir(){ busybox mkdir $args }
function bmktemp(){ busybox mktemp $args }
function bmv(){ busybox mv $args }
function bnc(){ busybox nc $args }
function bnl(){ busybox nl $args }
function bnproc(){ busybox nproc $args }
function bod(){ busybox od $args }
function bpaste(){ busybox paste $args }
function bpatch(){ busybox patch $args }
function bpgrep(){ busybox pgrep $args }
function bpidof(){ busybox pidof $args }
function bpipe_progress(){ busybox pipe_progress $args }
function bpkill(){ busybox pkill $args }
function bprintenv(){ busybox printenv $args }
function bprintf(){ busybox printf $args }
function bps(){ busybox ps $args }
function bpwd(){ busybox pwd $args }
function breadlink(){ busybox readlink $args }
function brealpath(){ busybox realpath $args }
function breset(){ busybox reset $args }
function brev(){ busybox rev $args }
function brm(){ busybox rm $args }
function brmdir(){ busybox rmdir $args }
function brpm(){ busybox rpm $args }
function brpm2cpio(){ busybox rpm2cpio $args }
function bsed(){ busybox sed $args }
function bseq(){ busybox seq $args }
function bsh(){ busybox sh $args }
function bsha1sum(){ busybox sha1sum $args }
function bsha256sum(){ busybox sha256sum $args }
function bsha3sum(){ busybox sha3sum $args }
function bsha512sum(){ busybox sha512sum $args }
function bshred(){ busybox shred $args }
function bshuf(){ busybox shuf $args }
function bsleep(){ busybox sleep $args }
function bsort(){ busybox sort $args }
function bsplit(){ busybox split $args }
function bssl_client(){ busybox ssl_client $args }
function bstat(){ busybox stat $args }
function bstrings(){ busybox strings $args }
function bsu(){ busybox su $args }
function bsum(){ busybox sum $args }
function bsync(){ busybox sync $args }
function btac(){ busybox tac $args }
function btail(){ busybox tail $args }
function btar(){ busybox tar $args }
function btee(){ busybox tee $args }
function btest(){ busybox test $args }
function btime(){ busybox time $args }
function btimeout(){ busybox timeout $args }
function btouch(){ busybox touch $args }
function btr(){ busybox tr $args }
function bTRUE(){ busybox TRUE $args }
function btruncate(){ busybox truncate $args }
function bts(){ busybox ts $args }
function btsort(){ busybox tsort $args }
function bttysize(){ busybox ttysize $args }
function buname(){ busybox uname $args }
function buncompress(){ busybox uncompress $args }
function bunexpand(){ busybox unexpand $args }
function buniq(){ busybox uniq $args }
function bunix2dos(){ busybox unix2dos $args }
function bunlink(){ busybox unlink $args }
function bunlzma(){ busybox unlzma $args }
function bunlzop(){ busybox unlzop $args }
function bunxz(){ busybox unxz $args }
function bunzip(){ busybox unzip $args }
function buptime(){ busybox uptime $args }
function busleep(){ busybox usleep $args }
function buudecode(){ busybox uudecode $args }
function buuencode(){ busybox uuencode $args }
function bvi(){ busybox vi $args }
function bwatch(){ busybox watch $args }
function bwc(){ busybox wc $args }
function bwget(){ busybox wget $args }
function bwhich(){ busybox which $args }
function bwhoami(){ busybox whoami $args }
function bwhois(){ busybox whois $args }
function bxargs(){ busybox xargs $args }
function bxxd(){ busybox xxd $args }
function bxz(){ busybox xz $args }
function bxzcat(){ busybox xzcat $args }
function byes(){ busybox yes $args }
function bzcat(){ busybox zcat $args }
function bls(){ busybox ls $args }
function bll(){ busybox ls -lh $args }
function bla(){ busybox ls -lah $args }
function bmd(){ busybox mkdir -p $args }
