function bar(){ busybox ar }
function barch(){ busybox arch }
function bascii(){ busybox ascii }
function bash(){ busybox ash }
function bawk(){ busybox awk }
function bbase32(){ busybox base32 }
function bbase64(){ busybox base64 }
function bbasename(){ busybox basename }
function bbash(){ busybox bash }
function bbc(){ busybox bc }
function bbunzip2(){ busybox bunzip2 }
function bbusybox(){ busybox busybox }
function bbzcat(){ busybox bzcat }
function bbzip2(){ busybox bzip2 }
function bcal(){ busybox cal }
function bcat(){ busybox cat }
function bchattr(){ busybox chattr }
function bchmod(){ busybox chmod }
function bcksum(){ busybox cksum }
function bclear(){ busybox clear }
function bcmp(){ busybox cmp }
function bcomm(){ busybox comm }
function bcp(){ busybox cp }
function bcpio(){ busybox cpio }
function bcrc32(){ busybox crc32 }
function bcut(){ busybox cut }
function bdate(){ busybox date }
function bdc(){ busybox dc }
function bdd(){ busybox dd }
function bdf(){ busybox df }
function bdiff(){ busybox diff }
function bdirname(){ busybox dirname }
function bdos2unix(){ busybox dos2unix }
function bdpkg(){ busybox dpkg }
function bdpkg-deb(){ busybox dpkg-deb }
function bdu(){ busybox du }
function becho(){ busybox echo }
function bed(){ busybox ed }
function begrep(){ busybox egrep }
function benv(){ busybox env }
function bexpand(){ busybox expand }
function bexpr(){ busybox expr }
function bfactor(){ busybox factor }
function bFALSE(){ busybox FALSE }
function bfgrep(){ busybox fgrep }
function bfind(){ busybox find }
function bfold(){ busybox fold }
function bfree(){ busybox free }
function bfsync(){ busybox fsync }
function bftpget(){ busybox ftpget }
function bftpput(){ busybox ftpput }
function bgetopt(){ busybox getopt }
function bgrep(){ busybox grep }
function bgroups(){ busybox groups }
function bgunzip(){ busybox gunzip }
function bgzip(){ busybox gzip }
function bhd(){ busybox hd }
function bhead(){ busybox head }
function bhexdump(){ busybox hexdump }
function bhttpd(){ busybox httpd }
function biconv(){ busybox iconv }
function bid(){ busybox id }
function binotifyd(){ busybox inotifyd }
function binstall(){ busybox install }
function bipcalc(){ busybox ipcalc }
function bjn(){ busybox jn }
function bkill(){ busybox kill }
function bkillall(){ busybox killall }
function bless(){ busybox less }
function blink(){ busybox link }
function bln(){ busybox ln }
function blogname(){ busybox logname }
function bls(){ busybox ls }
function blsattr(){ busybox lsattr }
function blzcat(){ busybox lzcat }
function blzma(){ busybox lzma }
function blzop(){ busybox lzop }
function blzopcat(){ busybox lzopcat }
function bmake(){ busybox make }
function bman(){ busybox man }
function bmd5sum(){ busybox md5sum }
function bmkdir(){ busybox mkdir }
function bmktemp(){ busybox mktemp }
function bmv(){ busybox mv }
function bnc(){ busybox nc }
function bnl(){ busybox nl }
function bnproc(){ busybox nproc }
function bod(){ busybox od }
function bpaste(){ busybox paste }
function bpatch(){ busybox patch }
function bpgrep(){ busybox pgrep }
function bpidof(){ busybox pidof }
function bpipe_progress(){ busybox pipe_progress }
function bpkill(){ busybox pkill }
function bprintenv(){ busybox printenv }
function bprintf(){ busybox printf }
function bps(){ busybox ps }
function bpwd(){ busybox pwd }
function breadlink(){ busybox readlink }
function brealpath(){ busybox realpath }
function breset(){ busybox reset }
function brev(){ busybox rev }
function brm(){ busybox rm }
function brmdir(){ busybox rmdir }
function brpm(){ busybox rpm }
function brpm2cpio(){ busybox rpm2cpio }
function bsed(){ busybox sed }
function bseq(){ busybox seq }
function bsh(){ busybox sh }
function bsha1sum(){ busybox sha1sum }
function bsha256sum(){ busybox sha256sum }
function bsha3sum(){ busybox sha3sum }
function bsha512sum(){ busybox sha512sum }
function bshred(){ busybox shred }
function bshuf(){ busybox shuf }
function bsleep(){ busybox sleep }
function bsort(){ busybox sort }
function bsplit(){ busybox split }
function bssl_client(){ busybox ssl_client }
function bstat(){ busybox stat }
function bstrings(){ busybox strings }
function bsu(){ busybox su }
function bsum(){ busybox sum }
function bsync(){ busybox sync }
function btac(){ busybox tac }
function btail(){ busybox tail }
function btar(){ busybox tar }
function btee(){ busybox tee }
function btest(){ busybox test }
function btime(){ busybox time }
function btimeout(){ busybox timeout }
function btouch(){ busybox touch }
function btr(){ busybox tr }
function bTRUE(){ busybox TRUE }
function btruncate(){ busybox truncate }
function bts(){ busybox ts }
function btsort(){ busybox tsort }
function bttysize(){ busybox ttysize }
function buname(){ busybox uname }
function buncompress(){ busybox uncompress }
function bunexpand(){ busybox unexpand }
function buniq(){ busybox uniq }
function bunix2dos(){ busybox unix2dos }
function bunlink(){ busybox unlink }
function bunlzma(){ busybox unlzma }
function bunlzop(){ busybox unlzop }
function bunxz(){ busybox unxz }
function bunzip(){ busybox unzip }
function buptime(){ busybox uptime }
function busleep(){ busybox usleep }
function buudecode(){ busybox uudecode }
function buuencode(){ busybox uuencode }
function bvi(){ busybox vi }
function bwatch(){ busybox watch }
function bwc(){ busybox wc }
function bwget(){ busybox wget }
function bwhich(){ busybox which }
function bwhoami(){ busybox whoami }
function bwhois(){ busybox whois }
function bxargs(){ busybox xargs }
function bxxd(){ busybox xxd }
function bxz(){ busybox xz }
function bxzcat(){ busybox xzcat }
function byes(){ busybox yes }
function bzcat(){ busybox zcat }
